import blockData from "./blocks.json";

export type Difficulty = "Easy" | "Medium" | "Hard";

export type BlockCategory = {
  id: string;
  name: string;
  difficulty: Difficulty;
  note: string;
};

/** The oldest Minecraft version blocks are tagged against, besides "later". */
export const LEGACY_VERSION = "1.16.5";

export type Block = {
  id: string;
  name: string;
  /** Average color of the block's texture. */
  color: string;
  /**
   * How far the texture's own pixels stray from that average color, in
   * redmean units — high for a patterned texture (ore flecks, a glaze, the
   * target block's bullseye) that never actually reads as one flat color.
   */
  noise: number;
  category: string;
  /**
   * Set when this is a block's other look: the cross-cut "end" of a log or
   * pillar, or the "top" of a block like sandstone. Left out for the main look.
   */
  face?: "end" | "top";
  /** Whether the block already existed in LEGACY_VERSION, or was added later. */
  since: typeof LEGACY_VERSION | "later";
};

// Difficulty is a rough guide to how hard the blocks are to gather.
export const categories: BlockCategory[] = [
  {
    id: "overworld",
    name: "Stone & earth",
    difficulty: "Easy",
    note: "Found on the surface or in shallow caves",
  },
  {
    id: "wood",
    name: "Wood",
    difficulty: "Easy",
    note: "Chop trees and craft",
  },
  {
    id: "wool",
    name: "Wool",
    difficulty: "Medium",
    note: "Sheep plus dyes for every color",
  },
  {
    id: "concrete",
    name: "Concrete",
    difficulty: "Medium",
    note: "Sand, gravel and dye, hardened in water",
  },
  {
    id: "concrete_powder",
    name: "Concrete powder",
    difficulty: "Medium",
    note: "Sand, gravel and dye, not yet hardened",
  },
  {
    id: "terracotta",
    name: "Terracotta",
    difficulty: "Medium",
    note: "Clay smelted and dyed",
  },
  {
    id: "glazed_terracotta",
    name: "Glazed terracotta",
    difficulty: "Medium",
    note: "Terracotta glazed in a furnace",
  },
  {
    id: "coral",
    name: "Dead coral blocks",
    difficulty: "Medium",
    note: "Warm oceans — silk-touch live coral, then let it dry out",
  },
  {
    id: "underground",
    name: "Underground & mined",
    difficulty: "Medium",
    note: "Deep caves, ores and crafted metal blocks",
  },
  {
    id: "sulfur",
    name: "Sulfur caves",
    difficulty: "Medium",
    note: "Found in the sulfur caves biome",
  },
  {
    id: "nether",
    name: "Nether",
    difficulty: "Hard",
    note: "Requires a trip to the Nether",
  },
  {
    id: "end",
    name: "The End",
    difficulty: "Hard",
    note: "Requires reaching the End",
  },
  {
    id: "ocean",
    name: "Ocean monument",
    difficulty: "Hard",
    note: "Only from ocean monuments and their guardians",
  },
  {
    id: "special",
    name: "Special finds",
    difficulty: "Hard",
    note: "Silk touch, ancient cities, pale gardens and more",
  },
  {
    id: "rare",
    name: "Rare & expensive",
    difficulty: "Hard",
    note: "Needs many gems or ingots per block",
  },
  {
    id: "creative",
    name: "Creative only",
    difficulty: "Hard",
    note: "Can't be obtained in survival",
  },
];

export type VersionFilter = "all" | typeof LEGACY_VERSION;

// Generated by scripts/generate-blocks.mjs from the Minecraft game files.
export const blocks = blockData as Block[];

/** Every block, keyed by id, for quick lookup once you only have an id. */
export const blocksById = new Map(blocks.map((block) => [block.id, block]));

/** Path of a block's texture, a 16x16 image in public/blocks. */
export const blockIcon = (block: Block) => `/blocks/${block.id}.png`;
